{
   "openapi":"3.0.1",
   "info":{
      "title":"FGTS - MP Desenrola 2.0 - Instituições Financeiras",
      "description":"Essa API tem como finalidade atender às Instituições Financeiras em conformidade com a MP nº 1.355/2026 do Programa Desenrola 2.0. \n\n# Authentication\n\n",
      "termsOfService":"https://api.caixa/terms",
      "contact":{
         "email":"cesoa020@caixa.gov.br"
      },
      "version":"1.0.0"
   },
   "servers":[
      {
         "url":"https://api.des.caixa:8443/fgts/mp-desenrola-20-if"
      }
   ],
   "paths":{
      "/v1/trabalhadores/solicitacoes-inclusao-divida/{cpf}":{
         "post":{
            "tags":[
               "Solicitações Desenrola 2.0"
            ],
            "summary":"Solicitar uma inclusão da informação de dívida.",
            "description":"Permite a Instituição Financeira solicitar uma inclusão da informação de dívida.",
            "parameters":[
               {
                  "name":"cpf",
                  "in":"path",
                  "description":"CPF do Trabalhador (sem formatação).",
                  "required":true,
                  "schema":{
                     "type":"string",
                     "minLength":11,
                     "maxLength":11
                  }
               },
               {
                  "name":"apikey",
                  "in":"header",
                  "description":"Secret da aplicação fornecido pela Caixa Econômica Federal para consumo da API.",
                  "required":true,
                  "schema":{
                     "type":"string"
                  }
               }
            ],
            "requestBody":{
               "description":"Body da solicitação de inclusão da informação de dívida.",
               "content":{
                  "application/json":{
                     "schema":{
                        "$ref":"#/components/schemas/InformacaoDivida"
                     }
                  }
               },
               "required":true
            },
            "responses":{
               "202":{
                  "description":"Sua solicitação foi recebida com sucesso para processamento na Caixa Econômica Federal. Retorna o protocolo da solicitação de inclusão da informação de dívida. Verificar status do protocolo para confirmar o resultado da operação.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Protocolo"
                        }
                     }
                  }
               },
               "400":{
                  "description":"3.CPF inválido. 4.Valor Original inválido. 5.Valor Renegociado inválido. 6.Valor de FGTS inválido. 7.Não é possível realizar a operação para o CPF informado.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "401":{
                  "description":"1.Usuário não autenticado.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "403":{
                  "description":"8.Instituição Financeira não possui autorização do Trabalhador para o Programa Desenrola 2.0.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "404":{
                  "description":"9.Trabalhador não localizado na base do FGTS.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "409":{
                  "description":"12.Existe uma Operação do Programa Desenrola 2.0 em andamento. Tente novamente mais tarde.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "500":{
                  "description":"2.Ocorreu um erro inesperado. Tente novamente mais tarde.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               }
            },
            "security":[
               {
                  "Internet":[
                     "mp_desenrola_2.0_if"
                  ],
                  "APIKey":[
                     
                  ]
               }
            ]
         }
      },
      "/v1/trabalhadores/protocolos/solicitacoes-exclusao-divida/{cpf}/{protocolo}":{
         "delete":{
            "tags":[
               "Solicitações Desenrola 2.0"
            ],
            "summary":"Solicitar uma exclusão da informação de dívida.",
            "description":"Permite a Instituição Financeira solicitar uma exclusão da informação de dívida.",
            "parameters":[
               {
                  "name":"cpf",
                  "in":"path",
                  "description":"CPF do Trabalhador (sem formatação).",
                  "required":true,
                  "schema":{
                     "type":"string",
                     "minLength":11,
                     "maxLength":11
                  }
               },
               {
                  "name":"protocolo",
                  "in":"path",
                  "description":"Protocolo da informação da dívida.",
                  "required":true,
                  "schema":{
                     "type":"integer",
                     "format":"int64",
                     "minimum":1
                  }
               },
               {
                  "name":"apikey",
                  "in":"header",
                  "description":"Secret da aplicação fornecido pela Caixa Econômica Federal para consumo da API.",
                  "required":true,
                  "schema":{
                     "type":"string"
                  }
               }
            ],
            "responses":{
               "202":{
                  "description":"Sua solicitação foi recebida com sucesso para processamento na Caixa Econômica Federal. Retorna o protocolo da solicitação de exclusão da informação de dívida. Verificar status do protocolo para confirmar o resultado da operação.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Protocolo"
                        }
                     }
                  }
               },
               "400":{
                  "description":"3.CPF inválido. 10.Protocolo inválido. 13.Já existe uma solicitação de exclusão da informação de dívida recebida ainda não processada.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "401":{
                  "description":"1.Usuário não autenticado.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "404":{
                  "description":"9.Trabalhador não localizado na base do FGTS. 11.Protocolo não localizado.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "409":{
                  "description":"12.Existe uma Operação do Programa Desenrola 2.0 em andamento. Tente novamente mais tarde.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "500":{
                  "description":"2.Ocorreu um erro inesperado. Tente novamente mais tarde.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               }
            },
            "security":[
               {
                  "Internet":[
                     "mp_desenrola_2.0_if"
                  ],
                  "APIKey":[
                     
                  ]
               }
            ]
         }
      },
      "/v1/trabalhadores/solicitacoes-consulta-saldo-liquido-simulado/{cpf}":{
         "post":{
            "tags":[
               "Solicitações Desenrola 2.0"
            ],
            "summary":"Solicitar uma consulta do saldo líquido simulado.",
            "description":"Permite a Instituição Financeira solicitar uma consulta do saldo líquido simulado.",
            "parameters":[
               {
                  "name":"cpf",
                  "in":"path",
                  "description":"CPF do Trabalhador (sem formatação).",
                  "required":true,
                  "schema":{
                     "type":"string",
                     "minLength":11,
                     "maxLength":11
                  }
               },
               {
                  "name":"apikey",
                  "in":"header",
                  "description":"Secret da aplicação fornecido pela Caixa Econômica Federal para consumo da API.",
                  "required":true,
                  "schema":{
                     "type":"string"
                  }
               }
            ],
            "responses":{
               "202":{
                  "description":"Sua solicitação foi recebida com sucesso para processamento na Caixa Econômica Federal. Retorna o protocolo da solicitação de consulta do saldo líquido simulado. Verificar status do protocolo para confirmar o resultado da operação.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Protocolo"
                        }
                     }
                  }
               },
               "400":{
                  "description":"3.CPF inválido. 7.Não é possível realizar a operação para o CPF informado.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "401":{
                  "description":"1.Usuário não autenticado.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "403":{
                  "description":"8.Instituição Financeira não possui autorização do Trabalhador para o Programa Desenrola 2.0.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "404":{
                  "description":"9.Trabalhador não localizado na base do FGTS.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "409":{
                  "description":"12.Existe uma Operação do Programa Desenrola 2.0 em andamento. Tente novamente mais tarde.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "500":{
                  "description":"2.Ocorreu um erro inesperado. Tente novamente mais tarde.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               }
            },
            "security":[
               {
                  "Internet":[
                     "mp_desenrola_2.0_if"
                  ],
                  "APIKey":[
                     
                  ]
               }
            ]
         }
      },
      "/v1/trabalhadores/protocolos/consultas-protocolo/{cpf}/{protocolo}":{
         "get":{
            "tags":[
               "Consultas Desenrola 2.0"
            ],
            "summary":"Consulta as informações do protocolo solicitado.",
            "description":"A consulta retorna o status do protocolo da solicitação de inclusão da informação de dívida, exclusao da informação de dívida ou da consulta do saldo líquido simulado.",
            "parameters":[
               {
                  "name":"cpf",
                  "in":"path",
                  "description":"CPF do Trabalhador (sem formatação).",
                  "required":true,
                  "schema":{
                     "type":"string",
                     "minLength":11,
                     "maxLength":11
                  }
               },
               {
                  "name":"protocolo",
                  "in":"path",
                  "description":"Protocolo da solicitação.",
                  "required":true,
                  "schema":{
                     "type":"integer",
                     "format":"int64",
                     "minimum":1
                  }
               },
               {
                  "name":"apikey",
                  "in":"header",
                  "description":"Secret da aplicação fornecido pela Caixa Econômica Federal para consumo da API.",
                  "required":true,
                  "schema":{
                     "type":"string"
                  }
               }
            ],
            "responses":{
               "200":{
                  "description":"Consulta realizada com sucesso.",
                  "content":{
                     "application/json":{
                        "examples":{
                           "inclusao":{
                              "summary":"Inclusão da informação de dívida",
                              "value":{
                                 "protocoloSolicitacao":1001,
                                 "tipoProtocolo":1,
                                 "dataHoraSolicitacao":"01/05/2026 10:00:00",
                                 "statusProtocolo":3,
                                 "vrOriginal":1000,
                                 "vrRenegociado":800,
                                 "vrFgts":500
                              }
                           },
                           "exclusao":{
                              "summary":"Exclusão da informação de dívida",
                              "value":{
                                 "protocoloSolicitacao":1002,
                                 "tipoProtocolo":2,
                                 "dataHoraSolicitacao":"02/05/2026 14:30:00",
                                 "statusProtocolo":3,
                                 "protocolo":456
                              }
                           },
                           "saldoLiquido":{
                              "summary":"Consulta de saldo líquido simulado",
                              "value":{
                                 "protocoloSolicitacao":1004,
                                 "tipoProtocolo":3,
                                 "dataHoraSolicitacao":"04/05/2026 16:45:20",
                                 "statusProtocolo":3,
                                 "dataHoraConsulta":"04/05/2026 16:47:05",
                                 "vrMaximoDebito":2150.75
                              }
                           }
                        },
                        "schema":{
                           "$ref":"#/components/schemas/ConsultaProtocolo"
                        }
                     }
                  }
               },
               "400":{
                  "description":"3.CPF inválido. 7.Não é possível realizar a operação para o CPF informado. 10.Protocolo inválido.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "401":{
                  "description":"1.Usuário não autenticado.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "403":{
                  "description":"8.Instituição Financeira não possui autorização do Trabalhador para o Programa Desenrola 2.0.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "404":{
                  "description":"9.Trabalhador não localizado na base do FGTS. 11.Protocolo não localizado.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               },
               "500":{
                  "description":"2.Ocorreu um erro inesperado. Tente novamente mais tarde.",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/Mensagem"
                        }
                     }
                  }
               }
            },
            "security":[
               {
                  "Internet":[
                     "mp_desenrola_2.0_if"
                  ],
                  "APIKey":[
                     
                  ]
               }
            ]
         }
      }
   },
   "components":{
      "schemas":{
         "InformacaoDivida":{
            "required":[
               "vrOriginal",
               "vrRenegociado",
               "vrFgts"
            ],
            "type":"object",
            "properties":{
               "vrOriginal":{
                  "type":"number",
                  "format":"decimal",
                  "minimum":0.01,
                  "multipleOf":0.01,
                  "description":"Valor Bruto devido pelo trabalhador para a Instituição Financeira no momento inicial antes da renegociação."
               },
               "vrRenegociado":{
                  "type":"number",
                  "format":"decimal",
                  "minimum":0.01,
                  "multipleOf":0.01,
                  "description":"Valor devido pelo trabalhador após a renegociação efetuada no âmbito do Programa Desenrola 2.0."
               },
               "vrFgts":{
                  "type":"number",
                  "format":"decimal",
                  "minimum":0.01,
                  "multipleOf":0.01,
                  "description":"Valor a ser debitado da conta de FGTS, para utilização no âmbito do Programa Desenrola 2.0."
               }
            }
         },
         "Protocolo":{
            "required":[
               "protocolo"
            ],
            "type":"object",
            "properties":{
               "protocolo":{
                  "type":"integer",
                  "format":"int64",
                  "minimum":1,
                  "description":"Identificador numérico de um protocolo gerado pela Caixa Econômica Federal em respostas de inclusão ou exclusão da informação de dívida ou de consulta do saldo líquido simulado, representa o protocolo associado à solicitação."
               }
            }
         },
         "ProtocoloBase":{
            "required":[
               "protocoloSolicitacao",
               "tipoProtocolo",
               "dataHoraSolicitacao",
               "statusProtocolo"
            ],
            "type":"object",
            "properties":{
               "protocoloSolicitacao":{
                  "type":"integer",
                  "format":"int64",
                  "minimum":1,
                  "description":"Protocolo da solicitação."
               },
               "tipoProtocolo":{
                  "type":"integer",
                  "enum":[
                     1,
                     2,
                     3
                  ],
                  "description":"Indica o Serviço correspondente ao Número do Protocolo informado. Opções: 1 - Inclusão da informação de dívida. 2 - Exclusão da informação de dívida. 3 - Consulta Saldo Líquido Simulado."
               },
               "dataHoraSolicitacao":{
                  "type":"string",
                  "description":"Data Hora de referência da Solicitação de Inclusão ou Exclusão da informação da dívida ou Consulta do Saldo Líquido Simulado no formato ."
               },
               "statusProtocolo":{
                  "type":"integer",
                  "enum":[
                     1,
                     2,
                     3,
                     4
                  ],
                  "description":"Status do Processamento da Transação. Pode ser: 1 – Recepcionada. Sua solicitação foi recepcionada. 2 – Em processamento. Sua solicitação encontra-se em processamento. 3 – Processada. Sua solicitação foi executada com sucesso. 4 – Rejeitada. Sua solicitação foi rejeitada."
               },
               "motivoStatus":{
                  "type":"string",
                  "description":"Motivo do Status do Protocolo caso o Status do Protocolo seja 4 - Rejeitada."
               }
            }
         },
         "ConsultaProtocolo":{
            "oneOf":[
               {
                  "$ref":"#/components/schemas/InformacoesDividaInclusao"
               },
               {
                  "$ref":"#/components/schemas/InformacoesDividaExclusao"
               },
               {
                  "$ref":"#/components/schemas/SaldoLiquidoSimulado"
               }
            ],
            "discriminator":{
               "propertyName":"tipoProtocolo",
               "mapping":{
                  "1":"#/components/schemas/InformacoesDividaInclusao",
                  "2":"#/components/schemas/InformacoesDividaExclusao",
                  "3":"#/components/schemas/SaldoLiquidoSimulado"
               }
            }
         },
         "InformacoesDividaInclusao":{
            "allOf":[
               {
                  "$ref":"#/components/schemas/ProtocoloBase"
               },
               {
                  "$ref":"#/components/schemas/InformacaoDivida"
               }
            ]
         },
         "InformacoesDividaExclusao":{
            "allOf":[
               {
                  "$ref":"#/components/schemas/ProtocoloBase"
               },
               {
                  "$ref":"#/components/schemas/Protocolo"
               }
            ]
         },
         "SaldoLiquidoSimulado":{
            "allOf":[
               {
                  "$ref":"#/components/schemas/ProtocoloBase"
               },
               {
                  "$ref":"#/components/schemas/SaldoLiquido"
               }
            ]
         },
         "SaldoLiquido":{
            "type":"object",
            "description":"Os campos dataHoraConsulta e vrMaximoDebito somente serão retornados quando o statusProtocolo for igual a 3 (Processada).\n",
            "properties":{
               "dataHoraConsulta":{
                  "type":"string",
                  "description":"Data Hora de referência do processamento da solicitação da Consulta do Saldo Líquido Simulado no formato . Preenchido apenas quando statusProtocolo = 3 (Processada)."
               },
               "vrMaximoDebito":{
                  "type":"number",
                  "format":"decimal",
                  "minimum":0,
                  "multipleOf":0.01,
                  "description":"Valor máximo para débito. Preenchido apenas quando statusProtocolo = 3 (Processada)."
               }
            }
         },
         "Mensagem":{
            "required":[
               "codigo",
               "descricao"
            ],
            "type":"object",
            "properties":{
               "codigo":{
                  "type":"integer",
                  "format":"int32",
                  "description":"Código do erro."
               },
               "descricao":{
                  "type":"string",
                  "description":"Descrição do erro."
               }
            }
         }
      },
      "securitySchemes":{
         "APIKey":{
            "description":"API Key do sistema que está chamando esta API.",
            "in":"header",
            "name":"APIKey",
            "type":"apiKey"
         },
         "Internet":{
            "description":"Tokens emitidos pelo realm INTERNET",
            "flows":{
               "clientCredentials":{
                  "refreshUrl":"https://logindes.caixa.gov.br/auth/realms/internet/protocol/openid-connect/token",
                  "scopes":{
                     "mp-desenrola-2.0-if":"Permite atender as Instituições Financeiras referente ao Programa Desenrola 2.0."
                  },
                  "tokenUrl":"https://logindes.caixa.gov.br/auth/realms/internet/protocol/openid-connect/token"
               }
            },
            "type":"oauth2"
         }
      }
   }
}